# Numpy


In [91]:
# Write a program to perform slicing of 2d array size 5x4 with desired outputs.

# Output 1: 6,7,8,11,12,13
# Output 2: 3, 4, 8, 9, 13, 14
# Output 3: 17, 18, 22, 23

import numpy as np

arr = np.array(
    [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24]
).reshape(5, 4)

print("The shape of array: ", arr.shape, "\n\n", arr)

print("\nOutput 1:\n", arr[1:3, 0:3])
print("\nOutput 2:\n", arr[:3, 2:])
print("\nOutput 3:\n", arr[3:, 1:3])

print("\narr[ -1: , -4:]: ", arr[-1:, -4:])
print("\narr[ -1:-4 , -4:-1]: ", arr[-1:-4, -4:-1])
print("\narr[ 2:3 , 3:4]: ", arr[2:3, 3:4])

The shape of array:  (5, 4) 

 [[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]

Output 1:
 [[ 6  7  8]
 [11 12 13]]

Output 2:
 [[ 3  4]
 [ 8  9]
 [13 14]]

Output 3:
 [[17 18]
 [22 23]]

arr[ -1: , -4:]:  [[21 22 23 24]]

arr[ -1:-4 , -4:-1]:  []

arr[ 2:3 , 3:4]:  [[14]]


In [1]:
# Write a program to create a database for an employee with the following details:
# Employee name
# Employee ID
# Employee salary
# Employee department
# DOB
# Blood Group
# Phone number

# Use numpy dtype for the code

import numpy as np

emp = np.dtype(
    [
        ("name", "U20"),
        ("id", "I"),
        ("salary", "I"),
        ("dept", "U20"),
        ("dob", "U20"),
        ("blood", "U20"),
        ("phone", "I"),
    ]
)

emp_details = np.array(
    [
        ("Rahul", 1, 10000, "IT", "10-10-1990", "B+ve", 1234567890),
        ("Raj", 2, 20000, "IT", "10-10-1991", "B+ve", 1234567890),
        ("Rohan", 3, 30000, "IT", "10-10-1992", "B+ve", 1234567890),
        ("Ramesh", 4, 40000, "IT", "10-10-1993", "B+ve", 1234567890),
        ("Rakesh", 5, 50000, "IT", "10-10-1994", "B+ve", 1234567890),
    ],
    dtype=emp,
)

print(emp_details)

[('Rahul', 1, 10000, 'IT', '10-10-1990', 'B+ve', 1234567890)
 ('Raj', 2, 20000, 'IT', '10-10-1991', 'B+ve', 1234567890)
 ('Rohan', 3, 30000, 'IT', '10-10-1992', 'B+ve', 1234567890)
 ('Ramesh', 4, 40000, 'IT', '10-10-1993', 'B+ve', 1234567890)
 ('Rakesh', 5, 50000, 'IT', '10-10-1994', 'B+ve', 1234567890)]
